[package]
name = "vad-masking"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
hound = { workspace = true }
hypr-data = { workspace = true }
rodio = { workspace = true }

[dependencies]
hypr-audio-utils = { workspace = true }
hypr-vad = { workspace = true, features = ["earshot"] }
