[package]
name = "model-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
hypr-cactus-model = { workspace = true }
hypr-download-interface = { workspace = true }
hypr-file = { workspace = true }

thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "fs", "sync"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
zip = "2"

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["time"] }
wiremock = { workspace = true }
